# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# YAML: $(NuGetApiKey)
# Powershell: $env:NUGETAPIKEY

trigger:
- master

pool:
  vmImage: 'windows-2019'

stages:
- stage: Deploy
  displayName: 'Publish to Powershell Gallery'
  jobs:
  - job: Publish
    continueOnError: false 
    steps:
      - Powershell: 'Install-PackageProvider -Name NuGet -Force ; & .\CI\Build.ps1'
        displayName: 'Installing pimcli on target'

      - Powershell: '.\CI\Publish.ps1'
        displayName: "Publish to Powershell Gallery"
        env: 
          NUGETAPIKEY: $(NuGetApiKey)

