# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# YAML: $(NuGetApiKey)
# Powershell: $env:NUGETAPIKEY
#
# Runs one job with several steps
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - LICENSE
    - .vscode

pool:
  vmImage: 'windows-2019'

stages:
- stage: Deploy
  displayName: 'Publish to Powershell Gallery'
  jobs:
  - job: Publish
    continueOnError: false 
    steps:
    - powershell: '.\CI\Pre-CheckCI.ps1'
      displayName: 'Pre check before publish'  

    - powershell: '.\CI\Build.ps1; Install-PackageProvider -Name NuGet -Force; & .\CI\Publish.ps1'
      displayName: 'Build module and publish to PSGallery'
      env: 
        NUGETAPIKEY: $(NuGetApiKey)

